---
dns_resolver_ips:
  - '1.1.1.1'
  - '8.8.8.8'
  - '9.9.9.9'

certgrinder_user: "certgrinder"
certgrinder_home: "/usr/local/etc/certgrinder"
node_exporter_textfile_path: "/var/tmp/node_exporter"
bootstrap_python: True

# this is the Python version of packages etc
python_version: "3.11"

# maybe don't edit below here
python_path: "/usr/local/bin/python{{ python_version }}"
python_nodotversion: "{{ python_version|replace('.','') }}"
python_versionstring: "Python {{ python_version }}"

network_interfaces_default:
  - description: "Upstream / outside interface"
    interface: "{{ ansible_default_ipv4.device }}"
    configure: False
    pf_macro: "if"
    pf_scrub: True
    pf_sync: False
    pf_carp: False
