---
- name: "Create supervisord.d config file to run prometheus"
  include_role:
    name: "supervisord_server"
    tasks_from: "supervisord.d"
  vars:
    supervisord_filename: "prometheus"
    supervisord_programs:
      - name: "prometheus"
        comment: "run prometheus"
        command: "/usr/local/bin/prometheus --config.file=/usr/local/etc/prometheus.yml --storage.tsdb.path=/var/db/prometheus --storage.tsdb.retention.time={{ prometheus_retention_days }}d --storage.tsdb.retention.size={{ prometheus_retention_size }} --web.external-url={{ prometheus_external_url }} --web.config.file=/usr/local/etc/prometheus-web.yml --web.enable-remote-write-receiver"
        user: "prometheus"

