---
- include_tasks: "packages.yml"
- include_tasks: "openntpd.yml"
- include_tasks: "smartd.yml"
  when: host_type == "hardware"
- include_tasks: "zfs-periodic.yml"
- include_tasks: "zfs-scrub.yml"
- include_tasks: "aesni.yml"
- include_tasks: "sysctl.yml"
- include_tasks: "arc_max.yml"
- include_tasks: "vmware.yml"
  when: host_type == "vmware"
- include_tasks: "accounting.yml"
- include_tasks: "htt.yml"
  tags:
    - "htt"
- include_tasks:
    file: "networkinterfaces.yml"
    apply:
      tags:
        - "network"
  when: network_interfaces is defined
  tags:
    - "network"
- include_tasks: "freebsd_sysctl_exporter.yml"
- include_tasks: "node_exporter_textfile_collector_smartmon.yml"
  when: host_type == 'hardware'
- include_tasks: "gstat_exporter.yml"
- include_tasks: "static_routes.yml"
  when: static_routes is defined
  tags:
    - "routing"
- include_tasks:
    file: "mobile_modem_exporter.yml"
    apply:
      tags:
        - "mobilemodem"
  when: mobile_modem_devices is defined
  tags:
    - "mobilemodem"
- include_tasks: "ppp.yml"
  when: ppp_profiles is defined
