---
- name: "Create supervisord.d config file to run uwsgi"
  include_role:
    name: "supervisord_server"
    tasks_from: "supervisord.d"
  vars:
    supervisord_filename: "uwsgi"
    supervisord_programs:
      - name: "uwsgi"
        comment: "run uwsgi"
        command: "/usr/local/bin/uwsgi --ini {{ uwsgi_configpath }} --virtualenv {{ uwsgi_virtualenv_path }}"
        user: "www"
        stopsignal: "INT"
        environment: "{{ uwsgi_environment }}"
