---
- name: "Configure Tor"
  template:
    src: "torrc.j2"
    dest: "{{ confpath }}"
  notify: "reload tor"

- name: "Set FIB for this Tor instance"
  sysrc:
    name: "tor_{% if instance.key != 'main' %}{{ instance.key }}_{% endif %}fib"
    value: "{{ instance.value.fib }}"
  tags: "tor"
  when:
    - instance.value.fib is defined
    - instance.value.fib != 0

- name: "Create onion service folders"
  file:
    path: "{{ datadir }}/{{ loopitem.name }}"
    state: "directory"
    owner: "_tor"
    group: "_tor"
    mode: "0700"
  loop: "{{ instance.value.onion_services | default([]) }}"
  loop_control:
    loop_var: "loopitem"
  notify: "reload tor"

- name: "Create client auth folder for each onion service running on this host"
  file:
    path: "{{ datadir }}/{{ loopitem.name }}/authorized_clients"
    state: "directory"
    owner: "_tor"
    group: "_tor"
    mode: "0700"
  loop: "{{ instance.value.onion_services | default([]) }}"
  loop_control:
    loop_var: "loopitem"
  notify: "reload tor"

- name: "Copy onion service client auth files (for onion services running on this host)"
  copy:
    dest: "{{ datadir }}/{{ loopitem.0.name }}/authorized_clients/{{ loopitem.1.name }}.auth"
    content: "descriptor:x25519:{{ loopitem.1.pubkey }}"
    owner: "_tor"
    group: "_tor"
    mode: "0600"
  with_subelements:
    - "{{ instance.value.onion_services }}"
    - auth_clients
  loop_control:
    loop_var: "loopitem"
  when:
    - "'onion_services' in instance.value.keys()"
  notify: "reload tor"

- name: "Create tor client onion auth folder (to contain keys for accessing onion services running on other hosts)"
  file:
    path: "{{ datadir }}/onion_auth"
    state: "directory"
    owner: "_tor"
    group: "_tor"
    mode: "0700"
  notify: "reload tor"

- name: "Copy onion service client auth files (keys for accessing onion services running on other hosts)"
  copy:
    dest: "{{ datadir }}/onion_auth/{{ loopitem.name }}.auth_private"
    content: "{{ loopitem.onion }}:descriptor:x25519:{{ loopitem.privkey }}"
    owner: "_tor"
    group: "_tor"
    mode: "0600"
  loop: "{{ instance.value.onion_client_auths|default([]) }}"
  loop_control:
    loop_var: "loopitem"
  when: "'onion_client_auths' in instance.value.keys()"
  notify: "reload tor"

- name: "Create exporter_exporter.d config file for MetricsPort for this Tor instance"
  include_role:
    name: "freebsd_base"
    tasks_from: "exporter_exporter.d"
  vars:
    expexp_filename: "tor-{{ instance.key }}-metrics.yml"
    expexp_program:
      method: "http"
      http:
        port: {{ instance.value.metricsport }}
