---
- name: "Install supervisord"
  pkgng:
    name: "py27-supervisor"
    state: "present"

- name: "Enable supervisord"
  service:
    name: "supervisord"
    enabled: yes
  notify:
    - "start supervisord"

- name: "Copy supervisor config"
  template:
    src: "supervisord.conf.j2"
    dest: "/usr/local/etc/supervisord.conf"
  notify:
    - "start supervisord"
    - "reread supervisord config"
    - "update supervisord config"

- name: "Create supervisord.d directory"
  file:
    path: "/usr/local/etc/supervisord.d"
    state: "directory"
    owner: "root"
    group: "wheel"
    mode: "0755"

