---
prometheus_retention_days: 3650
prometheus_retention_size: 0
prometheus_alertmanager_scheme: "http"
prometheus_basic_auth_users: []

nginx_locationslash: |
 location / {
      proxy_pass http://127.0.0.1:9090;
      proxy_http_version 1.1;
      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }


