{
 "title": "Prometheus Alerts Template",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Dashboard Title",
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h1>My Alert Overview</h1></center>"
   }
  },
  {
   "title": "Total Alert Count",
   "type": "stat",
   "gridPos": { "h": 11, "w": 4, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(ALERTS)" }
   ]
  },
  {
   "title": "Alerts per instance",
   "type": "table",
   "gridPos": { "h": 11, "w": 5, "x": 9, "y": 0 },
   "targets": [
    { "expr": "ALERTS" }
   ]
  },
  {
   "title": "Alerts per job",
   "type": "table",
   "gridPos": { "h": 11, "w": 5, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(ALERTS, \"job\", \"no job label found\", \"job\", \"\")"
    }
   ]
  },
  {
   "title": "Alerts per severity",
   "type": "table",
   "gridPos": { "h": 11, "w": 5, "x": 19, "y": 0 },
   "targets": [
    { "expr": "ALERTS" }
   ]
  },
  { "title": "Date & Time", "type": "grafana-clock-panel", "gridPos": { "h": 8, "w": 5, "x": 0, "y": 3 } },
  {
   "title": "All alerts",
   "type": "table",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "label_replace(ALERTS, \"job\", \"no job label found\", \"job\", \"\")"
    }
   ]
  }
 ]
}