#!/bin/sh
# $UPSNAME is set in the environment by upsmon
(echo "Notify from upsmon@$(/bin/hostname): $*" && /bin/echo && /bin/echo "This email generated by $0 at $(/bin/date)" && /bin/echo && /bin/echo "output from upsc ${UPSNAME}:" && /usr/local/bin/upsc ${UPSNAME}) | /usr/bin/mail -s "upsmon@$(/bin/hostname): $*" {{ nut_upsmon_notify_email }}

